# the image will be at ghcr.io/yourusername/name
name: cerulean

# what native container image to build on top of
# images not built by ublue might function unexpectly
base-container: ghcr.io/ublue-os/kinoite-main

# what fedora version to use, you can just change this to the next version update
# if you change this to "latest", you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do)
fedora-version: 38

# this description will be visible in the containers metadata
description: A bespoke Fedora Kinoite install.

# these rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  - python3-pip # needed for yafti (the first boot installer)
  - clamav-freshclam
  - clamd
  - clamtk
  - cups-pdf
  - distrobox
  - fcitx5-chinese-addons
  - fcitx5-configtool
  - fcitx5-gtk
  - fcitx5-qt
  - fcitx5-table-extra
  - fcitx5-table-other
  - gimagereader-qt
  - hunspell-fr
  - igt-gpu-tools
  - kcron
  - libreoffice
  - libreoffice-kf5
  - libva-utils
  - libvirt-client
  - lm_sensors
  - mono-core
  - neofetch
  - plasma-nm-fortisslvpn
  - python3-libguestfs
  - seahorse
  - skanpage
  - squashfs-tools
  - syncthing
  - tesseract-langpack-chi_sim
  - tesseract-langpack-chi_tra
  - tesseract-langpack-fra
  - virt-manager

# these flatpaks (from flathub) will be available for install on boot
# this is just an example selection, and even if you leave it empty,
# you'll have the basic options available in yafti
flatpaks:
- ca.hamaluik.Timecop
- ch.theologeek.Manuskript
- com.authy.Authy
- com.borgbase.Vorta
- com.discordapp.Discord
- com.github.PintaProject.Pinta
- com.github.zocker_160.SyncThingy
- com.moonlight_stream.Moonlight
- com.parsecgaming.parsec
- com.skype.Client
- com.valvesoftware.Steam
- com.wire.WireDesktop
- in.srev.guiscrcpy
- io.crow_translate.CrowTranslate
- io.github.dosbox-staging
- io.github.giantpinkrobots.bootqt
- io.github.jacalz.rymdport
- org.atheme.audacious
- org.chromium.Chromium
- org.chromium.Chromium.Codecs
- org.freeplane.App
- org.keepassxc.KeePassXC
- org.mozilla.Thunderbird
- org.prismlauncher.PrismLauncher
- org.signal.Signal
- org.telegram.desktop
- org.telegram.desktop.webview
- org.videolan.VLC
- org.zotero.Zotero
- us.zoom.Zoom
