# image will be published to ghcr.io/<user>/<name>
name: startingpoint
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: modules_config/main.yml
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
