# The akmods module is a tool used for managing and installing kernel modules built by Universal Blue. It simplifies the installation of kernel modules, improving the capabilities of your system.

# Only Universal Blue based images are officially supported. Universal Blue builds with Fedora 38 & below are not supported. Custom kernels are not supported.
type: akmods
install:
  #- openrazer
  #- openrgb
  #- v4l2loopback
  #- winesync
