# The "files" module simplifies the process of copying files to the image during the build time. These files are sourced from the "config/files" directory, which is located at "/tmp/config/files" inside the image.

type: files
files:
  - usr: /usr # copy static configurations
              # configuration you wish to end up in /etc/ on the booted system should be
              # added into /usr/etc/ as that is the proper "distro" config directory on ostree
              # read more in the files module's README
