# The "script" module can be used to run arbitrary scripts at image build time that take no or minimal external configuration (in the form of command line arguments). The scripts, which are run from the "config/scripts" directory, are declared under "scripts".

type: script
scripts: 
# this sets up the proper policy & signing files for signed images to work
   #- signing.sh 
