!include /usr/share/ublue-os/just/100-bling.just

### Useful features ###
#
# 1. Hide just script from "just" prompt, but make it still available by using [private] string above the just script name.
#       Documentation: https://just.systems/man/en/chapter_49.html?highlight=private#private-recipes
#
#       Example:
#
#       [private]
#       private-script:
#       #!/usr/bin/env bash
#       echo "Hello world!"

# Include some of your custom scripts here!
