# This workflow builds every branch of the repository daily at 16:30 UTC, one hour after ublue-os/nvidia builds.
# The images are also built after pushing changes or pull requests.
# The builds can also be triggered manually in the Actions tab thanks to workflow dispatch.
# Only the branch called `live` is published.


name: build-ublue
on: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  schedule:
    - cron: "30 16 * * *"
  push:
    branches:
      - live
      - template
      - main
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
  pull_request:
  workflow_dispatch:

# Only deploys the branch named "live". Ignores all other branches, to allow
# having "development" branches without interfering with GHCR image uploads.
jobs:
  ublue-build:
    name: Template Containerfile
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    container:
      image: registry.gitlab.com/wunker-bunker/ublue-cli:0.3.5-test-alpine
    strategy:
      fail-fast: false

      matrix:
# !!!
        # Add recipes for all the images you want to build here.
        # Don't add module configuration files, you will get errors.
        recipe:
          - recipe.yml
# !!!

    steps:
      - uses: actions/checkout@v2

      - name: Template Containerfile
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}
        run: |
          ublue build -vv ./config/${{ matrix.recipe }}

      - name: Echo outputs
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/live'
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
